"""add custom bool props for a wish

Revision ID: 454d7bbc4737
Revises: 578bffa2c151
Create Date: 2025-02-06 19:05:18.940853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454d7bbc4737'
down_revision: Union[str, None] = '578bffa2c151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('is_secret', sa.Boolean(), nullable=True))
    op.add_column('wishes', sa.Column('is_gifted', sa.Boolean(), nullable=True))
    op.drop_column('wishes', 'reserved')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('reserved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('wishes', 'is_gifted')
    op.drop_column('wishes', 'is_secret')
    # ### end Alembic commands ###
