"""add reserved bool field to wishes

Revision ID: 578bffa2c151
Revises: a245bca93919
Create Date: 2025-02-06 14:24:24.096839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578bffa2c151'
down_revision: Union[str, None] = 'a245bca93919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('reserved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishes', 'reserved')
    # ### end Alembic commands ###
